import { FormEvent, useEffect, useState } from "react";
import { Activity, BrainCircuit, CheckCircle2, ChevronRight, CircleDot, ShieldCheck, Sparkles } from "lucide-react";
import "./styles.css";

type Action = { actionId: string; riskLevel: string; target: string; requestedOperation: string; requiredAuthority: string; approvalState: string };
type Result = { ok: boolean; model?: string; text?: string; error?: string; plan?: { taskId: string; domain: string; specialists: string[]; riskLevel: string }; action?: Action };
const stages = ["PERCEIVE", "WORLD MODEL", "RESEARCH", "REASON", "PLAN", "RISK", "VERIFY", "ACTION GATE"];
const starterPrompts = ["Assess the current ArchOS architecture and identify the highest-value next implementation.", "Design a governed multi-agent workflow for a UAE world-model query.", "Propose an energy optimization and route any consequential operation through ActionGate."];

async function json<T>(url: string, init?: RequestInit): Promise<T> { const response = await fetch(url, init); return response.json(); }
async function askArchOS(prompt: string): Promise<Result> { return json<Result>("/api/reason", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ prompt }) }); }

export default function App() {
  const [prompt, setPrompt] = useState(""); const [result, setResult] = useState<Result | null>(null); const [busy, setBusy] = useState(false); const [pending, setPending] = useState<Action[]>([]);
  const refreshPending = async () => { try { const data = await json<{ actions: Action[] }>("/api/governance/pending"); setPending(data.actions ?? []); } catch { /* gateway offline */ } };
  useEffect(() => { refreshPending(); }, []);
  async function submit(event?: FormEvent) { event?.preventDefault(); const value = prompt.trim(); if (!value || busy) return; setBusy(true); setResult(null); try { const next = await askArchOS(value); setResult(next); await refreshPending(); } catch { setResult({ ok: false, error: "Unable to reach the ArchOS reasoning gateway." }); } finally { setBusy(false); } }
  async function approve(actionId: string) { await json(`/api/governance/${actionId}/approve`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ approver: "operator" }) }); await refreshPending(); }
  const activeStage = busy ? 3 : result ? (result.action ? 7 : 6) : -1;

  return <main className="shell">
    <header className="topbar"><div className="brand"><div className="brand-orb"><Sparkles size={18} /></div><div><strong>ARCHOS</strong><span>ULTRON // GEMINI COMMAND CENTER</span></div></div><div className="status"><CircleDot size={12} /> JARVIS RUNTIME <b>ONLINE</b></div></header>
    <section className="hero"><div className="hero-copy"><div className="eyebrow"><Activity size={14} /> SOVEREIGN INTELLIGENCE RUNTIME / ONLINE</div><h1>Reason with <span>Gemini.</span><br />Orchestrate with ArchOS.</h1><p>Gemini provides model reasoning. JARVIS owns orchestration, the canonical world model, governance, verification and the ActionGate boundary. ULTRON is the experience surface.</p></div><div className="architecture-card"><div className="node active"><BrainCircuit size={17} /><span>JARVIS</span><small>ORCHESTRATOR</small></div><ChevronRight /><div className="node"><Sparkles size={17} /><span>GEMINI</span><small>MODEL LAYER</small></div><ChevronRight /><div className="node"><ShieldCheck size={17} /><span>ACTION GATE</span><small>GOVERNANCE</small></div></div></section>
    <section className="pipeline panel"><div className="panel-title"><span>LIVE MISSION PIPELINE</span><small>{result?.plan?.taskId ?? "STANDBY"}</small></div><div className="stages">{stages.map((stage, i) => <div className={`stage ${i <= activeStage ? "active" : ""} ${i === activeStage ? "current" : ""}`} key={stage}><span>{String(i + 1).padStart(2, "0")}</span><b>{stage}</b></div>)}</div></section>
    <section className="workspace"><aside className="panel prompt-panel"><div className="panel-title"><span>COMMAND INPUT</span><small>01</small></div><form onSubmit={submit}><textarea value={prompt} onChange={e => setPrompt(e.target.value)} placeholder="Ask JARVIS to reason about architecture, world state, or an implementation..." /><button disabled={busy || !prompt.trim()}>{busy ? "REASONING..." : "EXECUTE MISSION"}<ChevronRight size={16} /></button></form><div className="starters"><span>QUICK MISSIONS</span>{starterPrompts.map(item => <button key={item} onClick={() => setPrompt(item)}>{item}<ChevronRight size={14} /></button>)}</div></aside>
      <section className="panel result-panel"><div className="panel-title"><span>INTELLIGENCE OUTPUT</span><small>{result?.model ?? "AWAITING INPUT"}</small></div>{!result && <div className="empty"><div className="pulse"><BrainCircuit size={30} /></div><h2>Awaiting mission</h2><p>The complete ArchOS reasoning path will be surfaced here.</p></div>}{result && <div className={`output ${result.ok ? "" : "error"}`}><div className="output-meta"><span>{result.ok ? "INFERENCE RECEIVED" : "GATEWAY ERROR"}</span><span>{result.plan?.domain ?? "SYSTEM"}</span></div>{result.plan && <div className="telemetry"><div><small>TASK</small><b>{result.plan.taskId}</b></div><div><small>RISK</small><b>{result.plan.riskLevel}</b></div><div><small>SPECIALISTS</small><b>{result.plan.specialists.length}</b></div></div>}<pre>{result.text ?? result.error}</pre></div>}</section>
    </section>
    <section className="panel approvals"><div className="panel-title"><span>ACTION GATE // PENDING APPROVALS</span><small>{pending.length} PENDING</small></div>{pending.length === 0 ? <div className="no-actions"><CheckCircle2 size={17} /> No consequential actions awaiting approval.</div> : pending.map(action => <div className="action-card" key={action.actionId}><div><b>{action.requestedOperation}</b><span>{action.target}</span><small>{action.riskLevel} · {action.requiredAuthority}</small></div><button onClick={() => approve(action.actionId)}>APPROVE <CheckCircle2 size={14} /></button></div>)}</section>
  </main>;
}
