import React, { useEffect, useMemo, useState } from 'react';
import { ChevronLeft, GitBranch, Pause, Play, RotateCcw, ShieldCheck, SkipBack, SkipForward, ChevronRight, X, GitCompare, GitFork, PlayCircle } from 'lucide-react';
import { missionReplay, type MissionReplaySession } from '../../aios/missionReplay';
import { sessionIntelligence } from '../../aios/sessionIntelligence';
import { temporalControlPlane, type TemporalComparison } from '../../aios/temporalControlPlane';
import { aiosRuntime } from '../../aios/runtime';
import { speechService } from '../../services/voice/speechService';

const SPEEDS = [0.5, 1, 2, 4] as const;
type Props = { open: boolean; onClose: () => void };
function formatRelative(ms: number): string { const total = Math.max(0, Math.floor(ms / 1000)); return `${Math.floor(total / 60).toString().padStart(2, '0')}:${(total % 60).toString().padStart(2, '0')}`; }
function eventLabel(kind: MissionReplaySession['frames'][number]['record']['kind']): string { return kind === 'world' ? 'WORLD' : kind.toUpperCase(); }
function commandTitle(command: MissionReplaySession['frames'][number]['record']['command']): string | null { return command?.type === 'REQUEST_EXECUTION' ? command.payload.title : null; }
function commandIntent(command: MissionReplaySession['frames'][number]['record']['command']): string | null { return command?.type === 'REQUEST_EXECUTION' ? command.payload.intent : null; }

export const UltronMissionReplay: React.FC<Props> = ({ open, onClose }) => {
  const [sessions, setSessions] = useState(sessionIntelligence.list()); const [sessionId, setSessionId] = useState<string | null>(null); const [compareId, setCompareId] = useState<string | null>(null); const [replay, setReplay] = useState<MissionReplaySession | null>(null); const [frameIndex, setFrameIndex] = useState(0); const [playing, setPlaying] = useState(false); const [speed, setSpeed] = useState<(typeof SPEEDS)[number]>(1); const [comparison, setComparison] = useState<TemporalComparison | null>(null); const [causalCount, setCausalCount] = useState(0); const [branchId, setBranchId] = useState<string | null>(null);
  useEffect(() => sessionIntelligence.subscribe(() => setSessions(sessionIntelligence.list())), []);
  useEffect(() => { if (!open) return; const active = sessionIntelligence.getActive(); setSessionId(current => current ?? active?.id ?? sessions.at(-1)?.sessionId ?? null); }, [open, sessions]);
  useEffect(() => { const next = sessionId ? missionReplay.getSession(sessionId) : null; setReplay(next); setFrameIndex(0); setPlaying(false); setComparison(null); setCausalCount(0); }, [sessionId]);
  useEffect(() => { if (!open || !playing || !replay?.frames.length) return; const frame = replay.frames[frameIndex]; const next = replay.frames[frameIndex + 1]; if (!next) { setPlaying(false); return; } const timer = window.setTimeout(() => setFrameIndex(index => Math.min(index + 1, replay.frames.length - 1)), Math.max(80, (next.timestamp - frame.timestamp) / speed)); return () => window.clearTimeout(timer); }, [open, playing, replay, frameIndex, speed]);
  useEffect(() => { if (sessionId && replay) temporalControlPlane.select(sessionId, frameIndex); }, [sessionId, frameIndex, replay]);
  const current = replay?.frames[frameIndex] ?? null; const progress = replay?.frames.length ? frameIndex / Math.max(1, replay.frames.length - 1) : 0; const selectedSummary = useMemo(() => sessions.find(item => item.sessionId === sessionId), [sessions, sessionId]);
  if (!open) return null;
  const seek = (value: number) => { const max = Math.max(0, (replay?.frames.length ?? 1) - 1); setFrameIndex(Math.min(max, Math.max(0, Math.round(value * max)))); };
  const inspect = () => { if (!current) return; aiosRuntime.setContext('replay', current.record.traceId, 'mission-replay', current.record.parentTraceId); speechService.speak(`Replay inspection. ${eventLabel(current.record.kind)} event at ${formatRelative(current.relativeMs)}.`); };
  const showCausal = () => { const chain = temporalControlPlane.causalChain(sessionId ?? undefined, frameIndex); setCausalCount(chain.length); speechService.speak(`Causal chain contains ${chain.length} events.`); };
  const createBranch = () => { if (!sessionId) return; const branch = temporalControlPlane.branchFrom(sessionId, frameIndex); if (branch) { setBranchId(branch.id); speechService.speak('Temporal branch created. Canonical history remains unchanged.'); } };
  const runBranch = () => { if (!branchId) return; temporalControlPlane.beginSimulation(branchId); speechService.speak('Simulation branch activated. Historical execution remains immutable.'); };
  const compare = () => { if (!sessionId || !compareId || sessionId === compareId) return; const result = temporalControlPlane.compare(sessionId, compareId); setComparison(result); speechService.speak(result ? `Mission comparison complete. ${result.sharedTraceIds.length} shared traces.` : 'Mission comparison unavailable.'); };

  return <div className="ultron-replay-shell" role="dialog" aria-modal="true" aria-label="ULTRON Mission Replay"><div className="ultron-replay-backdrop" onClick={onClose}/><section className="ultron-replay-panel">
    <header className="ultron-replay-header"><div><span className="ultron-replay-kicker"><span/> ULTRON / TEMPORAL CONTROL PLANE</span><h2>Mission Replay</h2><p>Reconstruct execution, inspect causality, compare missions, and branch safely from historical state.</p></div><button className="ultron-replay-close" onClick={onClose} aria-label="Close replay"><X/></button></header>
    <div className="ultron-replay-grid"><aside className="ultron-replay-sessions"><div className="ultron-replay-section-title">SESSIONS <span>{sessions.length}</span></div>{sessions.length === 0 && <div className="ultron-replay-empty">No recorded missions yet.</div>}{sessions.slice().reverse().map(item => <button key={item.sessionId} className={item.sessionId === sessionId ? 'is-active' : ''} onClick={() => setSessionId(item.sessionId)}><span className="session-status" data-status={item.status}/><strong>{item.sessionId.slice(0, 8)}</strong><small>{item.commandCount} commands · {item.status}</small><em>{new Date(item.startedAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</em></button>)}</aside>
      <main className="ultron-replay-main"><div className="ultron-replay-metrics"><div><span>MISSION</span><strong>{selectedSummary?.sessionId.slice(0, 12) ?? '—'}</strong></div><div><span>FRAMES</span><strong>{replay?.frames.length ?? 0}</strong></div><div><span>TRACE IDS</span><strong>{replay?.traceIds.length ?? 0}</strong></div><div><span>INTEGRITY</span><strong className={replay?.integrityValid ? 'is-good' : 'is-bad'}>{replay?.integrityValid ? 'VALID' : 'DEGRADED'}</strong></div></div>
        <div className="ultron-replay-track-wrap"><div className="ultron-replay-track" onClick={e => { const rect = e.currentTarget.getBoundingClientRect(); seek((e.clientX - rect.left) / rect.width); }}><span className="ultron-replay-track-fill" style={{ width: `${progress * 100}%` }}/>{(replay?.frames ?? []).map((frame, index) => <button key={frame.record.id} className={`replay-marker replay-${frame.record.kind}`} style={{ left: `${((replay?.frames.length ?? 1) === 1 ? 0 : index / ((replay?.frames.length ?? 1) - 1)) * 100}%` }} onClick={e => { e.stopPropagation(); setFrameIndex(index); }} aria-label={`Frame ${index + 1}`}/>)}<span className="ultron-replay-playhead" style={{ left: `${progress * 100}%` }}/></div><div className="ultron-replay-time"><span>00:00</span><strong>{current ? formatRelative(current.relativeMs) : '00:00'}</strong><span>{replay?.frames.at(-1) ? formatRelative(replay.frames.at(-1)!.relativeMs) : '00:00'}</span></div></div>
        <div className="ultron-replay-controls"><button onClick={() => setFrameIndex(0)}><SkipBack/></button><button onClick={() => setFrameIndex(i => Math.max(0, i - 1))}><ChevronLeft/></button><button className="replay-play" onClick={() => setPlaying(value => !value)} disabled={!replay?.frames.length}>{playing ? <Pause/> : <Play/>}</button><button onClick={() => setFrameIndex(i => Math.min((replay?.frames.length ?? 1) - 1, i + 1))}><ChevronRight/></button><button onClick={() => setFrameIndex(Math.max(0, (replay?.frames.length ?? 1) - 1))}><SkipForward/></button><span className="replay-control-divider"/>{SPEEDS.map(value => <button key={value} className={speed === value ? 'is-speed' : ''} onClick={() => setSpeed(value)}>{value}×</button>)}</div>
        <div className="ultron-replay-event"><div className="replay-event-top"><span>{current ? eventLabel(current.record.kind) : 'NO FRAME'}</span><span>{current?.record.status?.toUpperCase() ?? 'IDLE'}</span></div><h3>{commandTitle(current?.record.command) ?? current?.record.agentId ?? current?.record.worldEntityId ?? 'Awaiting replay frame'}</h3><p>{commandIntent(current?.record.command) ?? (current?.record.phase ? `Intelligence phase: ${current.record.phase}` : current?.record.payload ? JSON.stringify(current.record.payload) : 'Select a frame to inspect its canonical execution record.')}</p><div className="replay-event-meta"><span>TRACE <b>{current?.record.traceId ?? '—'}</b></span><span>PARENT <b>{current?.record.parentTraceId?.slice(0, 12) ?? 'ROOT'}</b></span><span>T+ <b>{current ? formatRelative(current.relativeMs) : '—'}</b></span></div></div>
        <div className="ultron-replay-actions"><button onClick={inspect}><GitBranch/> Inspect context</button><button onClick={showCausal}><GitCompare/> Causal chain {causalCount ? `(${causalCount})` : ''}</button><button onClick={createBranch}><GitFork/> Branch from state</button>{branchId && <button onClick={runBranch}><PlayCircle/> Run simulation branch</button>}<span className="replay-integrity"><ShieldCheck/> {replay?.missingTraceIds.length ? `${replay.missingTraceIds.length} MISSING TRACES` : 'TRACE RECONCILED'}</span></div>
        <div className="ultron-temporal-tools"><div><label>COMPARE WITH</label><select value={compareId ?? ''} onChange={e => setCompareId(e.target.value || null)}><option value="">Select mission…</option>{sessions.filter(item => item.sessionId !== sessionId).map(item => <option key={item.sessionId} value={item.sessionId}>{item.sessionId.slice(0, 12)} · {item.commandCount} commands</option>)}</select><button onClick={compare}><GitCompare/> Compare</button></div>{comparison && <div className="ultron-temporal-result"><span>{comparison.sharedTraceIds.length} SHARED</span><span>{comparison.leftOnlyTraceIds.length} LEFT ONLY</span><span>{comparison.rightOnlyTraceIds.length} RIGHT ONLY</span><span>{comparison.commonEventKinds.length} COMMON EVENT TYPES</span></div>}</div>
      </main></div>
  </section></div>;
};
